### ISSUE TITLE
ValueError: shapes (40,7360) and (15200,1) not aligned: 7360 (dim 1) != 15200 (dim 0)

### ISSUE THREAD

**Issue by Maggie-Jing** [chimera0/accel-brain-code#16] opened 2020-08-10 12:38 UTC
I run demo got this error, how do I set the parameters of this function 'ConditionalGANComposer()'

    midi_path_list=[
    "D:\\test\\Automatic Composition\\test.mid"

    ],
    # Batch size.
    batch_size=40,
    # The length of sequence that LSTM networks will observe.
    seq_len=8,
    # Learning rate in `Generator` and `Discriminator`.
    learning_rate=1e-10,
    # Time fraction or time resolution (seconds).
    time_fraction=0.5,
    )

```
Iterations: (1/1000)
----------------------------------------------------------------------------------------------------
The 'discriminator''s turn.
----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "D:/Git clone/audio-tech/projects/projects_hybrid/CloudMusician/PythonScripts/AnalysisMIDIFile/pycomposer_test.py", line 35, in <module>
    k_step=10
  File "D:\software\Anaconda3\lib\site-packages\pycomposer\gancomposable\conditional_gan_composer.py", line 335, in learn
    k_step=k_step
  File "D:\software\Anaconda3\lib\site-packages\pygan\generative_adversarial_networks.py", line 89, in train
    d_logs_list
  File "D:\software\Anaconda3\lib\site-packages\pygan\generative_adversarial_networks.py", line 139, in train_discriminator
    true_posterior_arr = discriminative_model.inference(true_arr)
  File "D:\software\Anaconda3\lib\site-packages\pygan\discriminativemodel\cnnmodel\seq_cnn_model.py", line 36, in inference
    return super().inference(observed_arr)
  File "D:\software\Anaconda3\lib\site-packages\pygan\discriminativemodel\cnn_model.py", line 141, in inference
    return self.__cnn.inference(observed_arr)
  File "pydbm\cnn\convolutional_neural_network.pyx", line 515, in pydbm.cnn.convolutional_neural_network.ConvolutionalNeuralNetwork.inference
  File "pydbm\cnn\convolutional_neural_network.pyx", line 554, in pydbm.cnn.convolutional_neural_network.ConvolutionalNeuralNetwork.forward_propagation
  File "pydbm\cnn\convolutional_neural_network.pyx", line 571, in pydbm.cnn.convolutional_neural_network.ConvolutionalNeuralNetwork.output_forward_propagate
ValueError: shapes (40,7360) and (15200,1) not aligned: 7360 (dim 1) != 15200 (dim 0)
````

**Comment by accel-brain** [comment] 2020-08-10 15:01
Update `pycomposer` to the latest version before use.

`pydbm` project is dormant. Instead, [accel-brain-base](https://github.com/accel-brain/accel-brain-code/tree/master/Accel-Brain-Base) project is in progress.

**Comment by accel-brain** [comment] 2020-08-10 15:03
The cause of this issue is unsupported and it is due to an old version, so we will close it.

**Closed as completed by accel-brain** 2020-08-10 15:03 UTC
