### ISSUE TITLE
how to get N number of sentences ?

### ISSUE THREAD

**Issue by JVK1987** [chimera0/accel-brain-code#14] opened 2020-07-21 09:18 UTC
Hi Team,

am using the pysummarization technique to summarize my document. with this library am able to get the top 10 ranked sentences only. if i need more then 10 ?

And how this 10 sentences this technique is picking also i am not clear on the document.

please help on these two things.

**Comment by accel-brain** [comment] 2020-07-21 12:24
#13

[#references](https://github.com/accel-brain/accel-brain-code/tree/master/Automatic-Summarization#references)

**Comment by JVK1987** [comment] 2020-07-22 05:49
Hi Team,

thank you for your replay.

i am little confused that, is pysummarization is abstractive or extractive summarization method.

thanks in advance

**Comment by accel-brain** [comment] 2020-07-22 07:07
In old natural language processing terms, this library basically performs an extraction (at least when you look at the functional output).

**Comment by JVK1987** [comment] 2020-07-22 07:16
Ok, so you mean this method is Extractive text summarization.

to understand more about this pysummarization method easily. can you share any link how the top 10 sentences its picking.

**Comment by chimera0** [comment] 2020-07-22 12:53
https://github.com/accel-brain/accel-brain-code/issues/14#issuecomment-661823566

**Comment by chimera0** [comment] 2020-07-22 13:00
This issue seems to be a duplicate of #15 .

**Comment by accel-brain** [comment] 2020-07-31 14:00
I’ll close this chat.

**Closed as completed by accel-brain** 2020-07-31 14:00 UTC
Labels: duplicate, question
